global:
  scrape_interval: 15s
  evaluation_interval: 15s


alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  - "model_alerts.yml"

scrape_configs:
  - job_name: "prometheus"


    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"
  - job_name: "machineinnovators"


    static_configs:
      - targets: ["host.docker.internal:8000"]
        labels:
          app: "machineinnovators"
